import type { AtlasSource } from "./types";

export const syntheticAlderFamily: AtlasSource = {
  schemaVersion: "1",
  assurance: "synthetic",
  title: "The Alder Family Atlas",
  subtitle: "Four generations of invented people, places, evidence, and unanswered questions.",
  provenanceNote: "Entirely fictional demonstration data. No person or relationship represents a real family.",
  people: [
    {
      id: "alder-elian",
      displayName: "Elian Alder",
      years: "1878–1951",
      lifeStatus: "deceased",
      generation: 0,
      order: 0,
      role: "Harbour cartographer",
      summary: "Mapped tidal channels and annotated the margins with weather, ships, and remembered stories.",
      place: "Bellweather Coast",
      evidence: "strongly_supported",
      sourceCount: 8,
      accent: "copper",
    },
    {
      id: "alder-mara",
      displayName: "Mara Alder",
      years: "1883–1964",
      lifeStatus: "deceased",
      generation: 0,
      order: 1,
      role: "Bookbinder and keeper of letters",
      summary: "Preserved voyage letters in hand-sewn folios whose dates anchor the earliest family timeline.",
      place: "Bellweather Coast",
      evidence: "strongly_supported",
      sourceCount: 11,
      accent: "moss",
    },
    {
      id: "alder-nora",
      displayName: "Nora Alder",
      years: "1907–1988",
      lifeStatus: "deceased",
      generation: 1,
      order: 0,
      role: "Teacher and oral historian",
      summary: "Recorded winter stories and family songs, carefully distinguishing memory from documented events.",
      place: "Northmere",
      evidence: "supported",
      sourceCount: 6,
      accent: "gold",
    },
    {
      id: "alder-silas",
      displayName: "Silas Alder",
      years: "1911–1976",
      lifeStatus: "deceased",
      generation: 1,
      order: 1,
      role: "Signal engineer",
      summary: "A railway ledger places him in Northmere, but one missing year keeps the migration route unresolved.",
      place: "Northmere",
      evidence: "unresolved",
      sourceCount: 4,
      accent: "clay",
    },
    {
      id: "alder-ivo",
      displayName: "Ivo Maren",
      years: "1909–1991",
      lifeStatus: "deceased",
      generation: 1,
      order: 2,
      role: "Printmaker",
      summary: "Joined the family through partnership; his studio marks appear on photographs and festival notices.",
      place: "Northmere",
      evidence: "supported",
      sourceCount: 5,
      accent: "moss",
    },
    {
      id: "alder-tomas",
      displayName: "Tomas Alder",
      years: "1934–2002",
      lifeStatus: "deceased",
      generation: 2,
      order: 0,
      role: "Coastal ecologist",
      summary: "Returned to the coast and indexed the family archive by place, date, source, and uncertainty.",
      place: "Bellweather Coast",
      evidence: "strongly_supported",
      sourceCount: 14,
      accent: "copper",
    },
    {
      id: "alder-lyra",
      displayName: "Lyra Maren",
      years: "1938–2011",
      lifeStatus: "deceased",
      generation: 2,
      order: 1,
      role: "Community archivist",
      summary: "Created the first source register and left several disputed captions visibly unresolved.",
      place: "Larkspur City",
      evidence: "strongly_supported",
      sourceCount: 17,
      accent: "gold",
    },
    {
      id: "alder-oren",
      displayName: "Oren Alder",
      years: "1961–2021",
      lifeStatus: "deceased",
      generation: 3,
      order: 0,
      role: "Restorer of maps",
      summary: "Digitised fragile charts and documented every repair so later readers could distinguish old marks from new.",
      place: "Larkspur City",
      evidence: "supported",
      sourceCount: 9,
      accent: "clay",
    },
    {
      id: "hidden-living-demo",
      displayName: "Hidden living person",
      years: "Private",
      lifeStatus: "living",
      generation: 4,
      order: 0,
      role: "Never projected",
      summary: "This record exists solely to prove public projection removes living people before layout.",
      evidence: "lead",
      sourceCount: 0,
    },
  ],
  relationships: [
    { id: "r1", from: "alder-elian", to: "alder-nora", kind: "parent", evidence: "strongly_supported" },
    { id: "r2", from: "alder-mara", to: "alder-nora", kind: "parent", evidence: "strongly_supported" },
    { id: "r3", from: "alder-elian", to: "alder-silas", kind: "parent", evidence: "supported" },
    { id: "r4", from: "alder-mara", to: "alder-silas", kind: "parent", evidence: "supported" },
    { id: "r5", from: "alder-nora", to: "alder-ivo", kind: "partner", evidence: "supported", label: "partners" },
    { id: "r6", from: "alder-nora", to: "alder-tomas", kind: "parent", evidence: "strongly_supported" },
    { id: "r7", from: "alder-ivo", to: "alder-tomas", kind: "adoptive_parent", evidence: "supported" },
    { id: "r8", from: "alder-silas", to: "alder-lyra", kind: "parent", evidence: "unresolved" },
    { id: "r9", from: "alder-tomas", to: "alder-oren", kind: "parent", evidence: "strongly_supported" },
    { id: "r10", from: "alder-lyra", to: "alder-oren", kind: "guardian", evidence: "supported" },
    { id: "hidden-r", from: "alder-oren", to: "hidden-living-demo", kind: "parent", evidence: "supported" },
  ],
  events: [
    {
      id: "e1",
      year: "1904",
      title: "The first surviving chart",
      description: "A tide map carries Elian's initials and Mara's later binding marks.",
      personIds: ["alder-elian", "alder-mara"],
      place: "Bellweather Coast",
      evidence: "strongly_supported",
    },
    {
      id: "e2",
      year: "1932–1934",
      title: "The Northmere interval",
      description: "A railway ledger and two letters disagree on the exact year of Silas's move.",
      personIds: ["alder-silas"],
      place: "Northmere",
      evidence: "unresolved",
    },
    {
      id: "e3",
      year: "1979",
      title: "The archive returns to the coast",
      description: "Tomas catalogues the family folios beside the harbour where the story began.",
      personIds: ["alder-tomas", "alder-lyra"],
      place: "Bellweather Coast",
      evidence: "supported",
    },
  ],
  researchQuestions: [
    {
      id: "q1",
      question: "Which year did Silas Alder leave Bellweather Coast?",
      status: "conflicted",
      nextAction: "Compare the railway payroll volume with the original letter envelopes, not later transcriptions.",
    },
    {
      id: "q2",
      question: "Who annotated the undated harbour photograph?",
      status: "next_search",
      nextAction: "Compare handwriting against Mara's folio labels and Lyra's later catalogue cards.",
    },
    {
      id: "q3",
      question: "Does the winter song predate Nora's recording?",
      status: "open",
      nextAction: "Search regional song collections and log negative results with coverage dates.",
    },
  ],
};
